/**
 * 🎯 Error Codes for API Responses
 * 
 * All API error messages should use these codes instead of hardcoded strings.
 * The UI will translate these codes using i18n.
 */

export const ERROR_CODES = {
  // Authentication
  AUTH_TOKEN_REQUIRED: 'AUTH_TOKEN_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_URL: 'INVALID_URL',
  INVALID_TIMEZONE: 'INVALID_TIMEZONE',
  
  // User Management
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_EXTERNAL_LOGIN: 'USER_EXTERNAL_LOGIN',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  
  // Organization
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_INACTIVE: 'ORGANIZATION_INACTIVE',
  USER_NOT_IN_ORGANIZATION: 'USER_NOT_IN_ORGANIZATION',
  
  // Sessions
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ACCESS_DENIED: 'SESSION_ACCESS_DENIED',
  
  // Public Participants
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_ALREADY_PROCESSED: 'PARTICIPANT_ALREADY_PROCESSED',
  INVALID_ACTION: 'INVALID_ACTION',
  PARTICIPANT_ACCESS_DENIED: 'PARTICIPANT_ACCESS_DENIED',
  
  // Password Reset
  RESET_TOKEN_REQUIRED: 'RESET_TOKEN_REQUIRED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_LINK_ALREADY_SENT: 'RESET_LINK_ALREADY_SENT',
  
  // Email
  EMAIL_SERVICE_NOT_CONFIGURED: 'EMAIL_SERVICE_NOT_CONFIGURED',
  EMAIL_SENT_SUCCESS: 'EMAIL_SENT_SUCCESS',
  
  // Plans & Limits
  PLAN_VERIFICATION_ERROR: 'PLAN_VERIFICATION_ERROR',
  USAGE_LIMIT_ERROR: 'USAGE_LIMIT_ERROR',
  ORGANIZATION_LIMITS_ERROR: 'ORGANIZATION_LIMITS_ERROR',
  UPGRADE_VERIFICATION_ERROR: 'UPGRADE_VERIFICATION_ERROR',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED',
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  PARTICIPANT_LIMIT_REACHED: 'PARTICIPANT_LIMIT_REACHED',
  TEAM_MEMBER_LIMIT_REACHED: 'TEAM_MEMBER_LIMIT_REACHED',
  PROJECT_MEMBER_LIMIT_REACHED: 'PROJECT_MEMBER_LIMIT_REACHED',
  
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  DATABASE_ERROR: 'DATABASE_ERROR',
  API_ERROR: 'API_ERROR'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]; 